/**
 * Client-side EventSphere certificate generator (no payment / no external URL required).
 * Creates a landscape PNG the student can download or print.
 */

function wrapText(ctx, text, x, y, maxWidth, lineHeight) {
  const words = String(text || '').split(/\s+/).filter(Boolean)
  let line = ''
  let cy = y
  for (let i = 0; i < words.length; i += 1) {
    const test = line ? `${line} ${words[i]}` : words[i]
    if (ctx.measureText(test).width > maxWidth && line) {
      ctx.fillText(line, x, cy)
      line = words[i]
      cy += lineHeight
    } else {
      line = test
    }
  }
  if (line) ctx.fillText(line, x, cy)
  return cy
}

/**
 * @returns {Promise<{ blob: Blob, filename: string }>}
 */
export async function buildCertificateImage({
  studentName,
  eventTitle,
  eventDate,
  issuedOn,
  organizerLabel = 'EventSphere Campus',
}) {
  const width = 1400
  const height = 990
  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height
  const ctx = canvas.getContext('2d')

  // Background
  const bg = ctx.createLinearGradient(0, 0, width, height)
  bg.addColorStop(0, '#0b0d18')
  bg.addColorStop(0.45, '#151936')
  bg.addColorStop(1, '#1a1430')
  ctx.fillStyle = bg
  ctx.fillRect(0, 0, width, height)

  // Soft orbs
  ctx.fillStyle = 'rgba(84,216,232,0.12)'
  ctx.beginPath()
  ctx.arc(220, 180, 160, 0, Math.PI * 2)
  ctx.fill()
  ctx.fillStyle = 'rgba(154,123,255,0.14)'
  ctx.beginPath()
  ctx.arc(1180, 780, 200, 0, Math.PI * 2)
  ctx.fill()

  // Outer frame
  ctx.strokeStyle = 'rgba(154,123,255,0.55)'
  ctx.lineWidth = 4
  ctx.strokeRect(48, 48, width - 96, height - 96)
  ctx.strokeStyle = 'rgba(84,216,232,0.35)'
  ctx.lineWidth = 1.5
  ctx.strokeRect(68, 68, width - 136, height - 136)

  // Brand
  ctx.fillStyle = '#54d8e8'
  ctx.font = '700 18px system-ui,Segoe UI,sans-serif'
  ctx.textAlign = 'center'
  ctx.fillText('EVENTSPHERE', width / 2, 130)
  ctx.fillStyle = 'rgba(210,212,227,0.7)'
  ctx.font = '500 13px system-ui,Segoe UI,sans-serif'
  ctx.fillText('SMART CAMPUS EVENT & ENGAGEMENT', width / 2, 156)

  ctx.fillStyle = '#f4f5ff'
  ctx.font = '600 42px Georgia, "Times New Roman", serif'
  ctx.fillText('Certificate of Participation', width / 2, 240)

  ctx.fillStyle = 'rgba(210,212,227,0.85)'
  ctx.font = '400 18px system-ui,Segoe UI,sans-serif'
  ctx.fillText('This certifies that', width / 2, 310)

  ctx.fillStyle = '#ffffff'
  ctx.font = '700 48px Georgia, "Times New Roman", serif'
  ctx.fillText(String(studentName || 'Participant').slice(0, 48), width / 2, 380)

  ctx.fillStyle = 'rgba(210,212,227,0.85)'
  ctx.font = '400 18px system-ui,Segoe UI,sans-serif'
  ctx.fillText('successfully participated in', width / 2, 440)

  ctx.fillStyle = '#cb8beb'
  ctx.font = '600 34px Georgia, "Times New Roman", serif'
  wrapText(ctx, String(eventTitle || 'Campus Event').slice(0, 80), width / 2, 500, 980, 42)

  const dateLine = eventDate ? `Event date: ${String(eventDate).slice(0, 10)}` : ''
  const issuedLine = issuedOn
    ? `Issued: ${new Date(issuedOn).toLocaleDateString()}`
    : `Issued: ${new Date().toLocaleDateString()}`
  ctx.fillStyle = 'rgba(210,212,227,0.75)'
  ctx.font = '400 16px system-ui,Segoe UI,sans-serif'
  ctx.fillText([dateLine, issuedLine].filter(Boolean).join('  ·  '), width / 2, 620)

  // Signature lines
  ctx.strokeStyle = 'rgba(255,255,255,0.25)'
  ctx.beginPath()
  ctx.moveTo(280, 780)
  ctx.lineTo(520, 780)
  ctx.moveTo(880, 780)
  ctx.lineTo(1120, 780)
  ctx.stroke()
  ctx.fillStyle = 'rgba(210,212,227,0.7)'
  ctx.font = '500 14px system-ui,Segoe UI,sans-serif'
  ctx.fillText('Organizer', 400, 810)
  ctx.fillText(String(organizerLabel).slice(0, 28), 1000, 810)

  ctx.fillStyle = 'rgba(154,123,255,0.9)'
  ctx.font = '600 12px system-ui,Segoe UI,sans-serif'
  ctx.fillText('Generated by EventSphere · not a payment receipt', width / 2, 900)

  const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/png'))
  const safeTitle = String(eventTitle || 'event')
    .replace(/[^\w\-]+/g, '_')
    .slice(0, 40)
  return {
    blob,
    filename: `EventSphere_Certificate_${safeTitle}.png`,
  }
}

export async function downloadCertificate(opts) {
  const { blob, filename } = await buildCertificateImage(opts)
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
  return { filename }
}

/** Opens a print-friendly dialog (browser → Save as PDF) via hidden iframe. */
export function printCertificate(opts) {
  const name = String(opts.studentName || 'Participant')
  const title = String(opts.eventTitle || 'Campus Event')
  const date = opts.eventDate ? String(opts.eventDate).slice(0, 10) : ''
  const issued = opts.issuedOn
    ? new Date(opts.issuedOn).toLocaleDateString()
    : new Date().toLocaleDateString()

  const html = `<!doctype html><html><head><meta charset="utf-8"/><title>Certificate — ${title}</title>
    <style>
      @page { size: landscape; margin: 16mm; }
      body { font-family: Georgia, serif; text-align: center; color: #111; padding: 40px; margin: 0; }
      .brand { letter-spacing: .2em; font-size: 12px; color: #555; font-family: system-ui,sans-serif; }
      h1 { font-size: 34px; margin: 28px 0 10px; }
      .name { font-size: 40px; margin: 24px 0; }
      .event { font-size: 26px; color: #4b3f8f; margin: 18px 0; }
      .meta { font-family: system-ui,sans-serif; font-size: 13px; color: #444; margin-top: 28px; }
      .frame { border: 3px solid #7c6bcf; padding: 36px; }
    </style></head><body>
    <div class="frame">
      <div class="brand">EVENTSPHERE · CAMPUS CERTIFICATE</div>
      <h1>Certificate of Participation</h1>
      <p>This certifies that</p>
      <div class="name">${name}</div>
      <p>successfully participated in</p>
      <div class="event">${title}</div>
      <div class="meta">${date ? `Event date: ${date} · ` : ''}Issued: ${issued}</div>
    </div>
    </body></html>`

  const iframe = document.createElement('iframe')
  iframe.setAttribute('aria-hidden', 'true')
  iframe.style.cssText =
    'position:fixed;right:0;bottom:0;width:0;height:0;border:0;opacity:0;pointer-events:none'
  document.body.appendChild(iframe)
  const doc = iframe.contentDocument || iframe.contentWindow?.document
  if (!doc) {
    iframe.remove()
    return { error: { message: 'Could not open print dialog' } }
  }
  doc.open()
  doc.write(html)
  doc.close()

  const runPrint = () => {
    try {
      iframe.contentWindow?.focus()
      iframe.contentWindow?.print()
    } finally {
      window.setTimeout(() => iframe.remove(), 1500)
    }
  }
  window.setTimeout(runPrint, 80)
  return { error: null }
}
